### ISSUE TITLE
Update to function component examples

### ISSUE THREAD

**Issue by williamngan** [williamngan/pts-react-example#27]
As [react-pts-canvas](https://github.com/williamngan/react-pts-canvas/) has been updated with functional components, this repo's examples should be updated to reflect the change.

**Comment by williamngan** [comment]
Hi @prkirby and @tibotiber - I've updated all the examples (see [PtsExamples.jsx](https://github.com/williamngan/pts-react-example/blob/master/example/src/PtsExamples.jsx)) in this repo to use the new <PtsCanvas> functional component. 

If you can have time to help review the code and send PR as needed, it would be great appreciated! 🙏

**Comment by tibotiber** [comment]
oh I didn't know about this repo, nifty :).

Seems like the build has botched the demo link. Pulled it locally, dev mode works, prod build as well. Not sure how github pages works nowadays so can't really help. I'm gonna skim through the new code example now, but admittedly I'm not used to the new syntax yet so it feels foreign.

**Comment by tibotiber** [comment]
I just have 10m so I'll write here first, I can PR later or anyone feel free to take it. Also let me know if you disagree, I went through super quick so might have missed stuff.

For the chart example, I'd have gone with [`useMemo`](https://reactjs.org/docs/hooks-reference.html#usememo) instead of `useRef`. It's the hook made to recompute expensive stuff based on declared dependencies.

For the animation example, I'd have gone with [`useState`](https://reactjs.org/docs/hooks-reference.html#usestate) instead of `useRef`. It's the hook made to recompute stuff based on events.

Cheers

**Comment by williamngan** [comment]
Thank you @tibotiber -- I'll give it a try. I have lots to learn in the new React way!

**Comment by tibotiber** [comment]
Good, this is a prime opportunity ;). Feel free to reach out with any question, happy to help! And if you're tight I can also do the PR, let me know.

**Comment by williamngan** [comment]
Hey @tibotiber - I tried your suggestions but couldn't get it to work. I'm guessing because the onAnimate handler will be passed into the `spaceRef` inside an `useEffect` (ie, [here](https://github.com/williamngan/react-pts-canvas/blob/master/src/index.tsx#L99)), so the props/states changes won't show up within the animate handler (maybe?). I also tried wrapping handleAnimate in a `useCallback`, but it didn't help either. 

Any thoughts on this?

```jsx
  const [noiseGrid, setNoiseGrid]  = useState([]);

  const reset = (space) => {
    const gd = Create.gridPts( space.innerBound, 20, 20 );
    setNoiseGrid( Create.noisePts( gd, 0.05, 0.1, 20, 20 ) );
  }

  const handleStart = (bound, space) => {
    reset(space);
  };

  const handleAnimate = (space, form, time) => {
    // !! not getting the latest noiseGrid state, it remains empty
    console.log( noiseGrid );
  }
```

**Comment by tibotiber** [comment]
Sorry for the late reply @williamngan, it's a rough couple of weeks. From what I see, it could be a bug in the new version, rather than the way you use it. Basically `spaceRef.current.add()` called [here](https://github.com/williamngan/react-pts-canvas/blob/master/src/index.tsx#L99) is running in a `useEffect` that only has `canvRef` as dependency. This means new handler props would not be applied on the space. I'm not super familiar with the new internals yet, maybe @prkirby could provide some thoughts on this?

**Comment by tibotiber** [comment]
The dependencies basically trigger re-execution of the effect when their value changes. So here we would expect the handlers to be added as dependencies. I can't recall if there are necessary tricks when the dependency is a function though. I usually test it out and visualise it with some logs.

**Comment by williamngan** [comment]
Thanks again @tibotiber. I fixed the demo code and it's now working well -- much better without `useRef`!
